Bootstrap my own system
I remade the profile for my system. For now, removing unused components.

Signed-off-by: Alexey Gladkov <legion@altlinux.org>

diff --git a/system/image-scripts.d/50-users b/system/image-scripts.d/50-users
--- a/system/image-scripts.d/50-users
+++ b/system/image-scripts.d/50-users
@@ -1,34 +1,41 @@
-#!/bin/sh -efu
+#!/bin/bash -efu
 
-#default_groups="cdwriter cdrom audio video proc radio floppy uucp wheel camera xgrp scanner"
-for g in adbusers camera scanner xgrp; do
-	groupadd -f -r "$g"
+PROG="${0##*/}"
+rc=0
+
+for login in ${INFO_USER_CREATE-}; do
+	if id "$login" >/dev/null 2>&1; then
+		printf >&2 '%s: ERROR: user "%s" already exist\n' "$PROG" "$login"
+		rc=1
+		continue
+	fi
+
+	eval "uid=\"\${INFO_USER_UID_${login}-}\""
+	eval "gid=\"\${INFO_USER_GID_${login}-}\""
+	eval "shell=\"\${INFO_USER_SHELL_${login}-}\""
+	eval "groups=\"\${INFO_USER_GROUPS_${login}-}\""
+	eval "need_hasher=\"\${INFO_USER_HASHER_${login}-}\""
+
+	[ -z "$gid" ] ||
+		groupadd -g "$gid" "$login"
+
+	useradd -M -F \
+		${uid:+--uid "$uid"} \
+		${gid:+--gid "$gid"} \
+		${shell:+--shell "$shell"} \
+		${groups:+--groups "$groups"} \
+		"$login"
+
+	mkdir -p "/home/$login"
+	chmod 0000 "/home/$login"
+
+	case "${need_hasher,,}" in
+		yes|true|1)
+			hasher-useradd "$login"
+			;;
+	esac
 done
 
-for u in gleb doppel; do
-	! id "$u" >/dev/null 2>&1 || exit 1
-	useradd "$u"
-	mkdir -p /home/"$u"
-	chmod 0000 /home/"$u"
-	mkdir -p /var/lib/systemd/linger
-	touch /var/lib/systemd/linger/"$u"
+usermod --home /home/root root
 
-	hasher-useradd "$u"
-done
-
-for u in gleb doppel; do
-	hasher-useradd "${u}_b"
-done
-
-for g in users xgrp; do
-	gpasswd -a gleb "$g"
-	gpasswd -a doppel "$g"
-done
-
-for g in adbusers netadmin proc uucp vmusers wheel; do
-	gpasswd -a gleb "$g"
-done
-
-for g in audio camera; do
-	gpasswd -a doppel "$g"
-done
+exit $rc
